# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Restart server
  ansible.builtin.reboot:
  become: true
  when:
    - inventory_hostname != "localhost"